# Generated by Django 4.2.7 on 2023-11-14 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'действие',
                'verbose_name_plural': 'действия',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'места',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_to_perform', models.DateTimeField(auto_now_add=True, verbose_name='время и дата, когда необходимо выполнять')),
                ('is_pleasure', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('periodicity', models.PositiveSmallIntegerField(default=1, verbose_name='периодичность в днях')),
                ('reward', models.CharField(blank=True, max_length=150, null=True, verbose_name='вознаграждение')),
                ('execution_time', models.PositiveSmallIntegerField(default=60, verbose_name='время на выполнение в секундах')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habit', to='habits.action', verbose_name='действие')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habit', to=settings.AUTH_USER_MODEL, verbose_name='создатель')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habit', to='habits.place', verbose_name='место')),
                ('pleasure_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='habits.habit', verbose_name='приятная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
                'ordering': ('pk',),
            },
        ),
    ]
